# Generated by Django 3.2.4 on 2022-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
