# Generated by Django 3.2.4 on 2022-02-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_drug_drug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='drug_name',
            new_name='name',
        ),
    ]
